version: "3"

vars:
  BUILD_DIR: build

# Suppress macOS malloc nano zone warning when using AddressSanitizer
# (nano allocator conflicts with ASan's memory layout, but fallback is harmless)
env:
  MallocNanoZone: 0

tasks:
  # --------------------------------------------------
  # Setup
  # --------------------------------------------------

  configure:
    desc: Configure CMake build directory
    cmds:
      - cmake -S . -B {{.BUILD_DIR}}
      # clangd looks for compile_commands.json in root directory
      - ln -sf {{.BUILD_DIR}}/compile_commands.json ./compile_commands.json

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}} compile_commands.json

  # --------------------------------------------------
  # Build
  # --------------------------------------------------

  build:
    desc: Build everything
    cmds:
      - cmake --build {{.BUILD_DIR}}

  build:bean:
    desc: Build Bean
    cmds:
      - cmake --build {{.BUILD_DIR}} --target bean

  build:scratch:
    desc: Build Scratch
    cmds:
      - cmake --build {{.BUILD_DIR}} --target scratch

  build:dodge:
    desc: Build Dodge
    cmds:
      - cmake --build {{.BUILD_DIR}} --target dodge

  # --------------------------------------------------
  # Run
  # --------------------------------------------------

  run:bean:
    desc: Run Bean
    deps: [build:bean]
    vars:
      LEDGER_PATH: data/simple.bean
    cmds:
      # - cd {{.BUILD_DIR}}/bean && ./bean check {{.LEDGER_PATH}}
      - ./{{.BUILD_DIR}}/bean/bean test bean/data/simple.bean

  run:scratch:
    desc: Run Scratch
    deps: [build:scratch]
    vars:
      STATS_PATH: data/stats.txt
    cmds:
      - cd {{.BUILD_DIR}}/scratch && ./scratch {{.STATS_PATH}}

  run:dodge:
    desc: Run Dodge
    deps: [build:dodge]
    cmds:
      - cd {{.BUILD_DIR}}/dodge && ./dodge

  # --------------------------------------------------
  # Test
  # --------------------------------------------------

  test:
    desc: Run all tests
    deps: [build]
    cmds:
      - cd {{.BUILD_DIR}} && ctest --output-on-failure

  test:math_lib:
    desc: Run math_lib tests
    cmds:
      - cmake --build {{.BUILD_DIR}} --target test_math_utils
      - cmake --build {{.BUILD_DIR}} --target test_foo
      - ./{{.BUILD_DIR}}/libs/math_lib/test_math_utils
      - ./{{.BUILD_DIR}}/libs/math_lib/test_foo

  # --------------------------------------------------
  # Tools
  # --------------------------------------------------

  format:
    desc: Run clang-format
    cmds:
      - |
        git ls-files '*.c' '*.h' | xargs clang-format -i

  lint:
    desc: Run clang-tidy (compile_commands.json must exist)
    cmds:
      # macOS only: --extra-arg to help clang-tidy find system headers
      - |
        git ls-files '*.c' '*.h' | xargs clang-tidy \
          --extra-arg=-isysroot --extra-arg=$(xcrun --show-sdk-path) \
          -p {{.BUILD_DIR}}
